### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by gdietz8** [yayajjiang/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - Please embed the link to the website the reader can use to download VSCode
- [x] All relevant code examples written with backticks (```)
  - make sure that all code and commands are written in code blocks using backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by yayajjiang** [comment]
For the second issue, all the code written with backticks, do you mean all the commands like `ls`, `cat`, or something like that? Or the screenshot of the commands. Thank you for the clarification.

**Comment by gdietz8** [comment]
Yes, exactly! For example, use backticks when referencing `cd`, `ls`, `ls -a`, etc, in your **Trying Some Commands** section. There's no need to edit the screenshots.

**Comment by yayajjiang** [comment]
Cool, thank you so much. I just updated the changes!

**Comment by gdietz8** [comment]
Make sure to submit a regrade request so I am able to update your grade!

From above:
If you don't have all the checkmarks above, fix the issues described, and then submit a regrade request on Gradescope. Use this template for your regrade request:

Link to this issue
Link to your published lab report page

**Comment by yayajjiang** [comment]
I just submitted the regrade request. Thank you so much!
